language: python
python:
  "3.8"

install:
  - pip install kart

before_script:
 - chmod +x ./_scripts/cibuild.sh
# Travis will run `bundle install` by default before running our script
script:
  - ./_scripts/cibuild.sh

exclude: [vendor]
sudo: false
