language: ruby
branches:
  only:
  - main
rvm:
- 2.7.0
before_script:
 - chmod +x ./_scripts/cibuild.sh
# Travis will run `bundle install` by default before running our script
script: ./_scripts/cibuild.sh
exclude: [vendor]
sudo: false
