language: python
python:
  "3.8"

before_script:
 - chmod +x ./_scripts/cibuild.sh
# Travis will run `bundle install` by default before running our script
script:
  - ./_scripts/cibuild.sh

deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: _site
  on:
    branch: main
