name: Giacomo Caironi
collections:
  projects:
    output: true
  tags:
    output: false

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "autopage_tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

feed:
  collections:
    - projects

pagination:
  enabled: true
  per_page: 1

autopages:
  enabled: true

  tags:
    layouts:
      - 'autopage_tag.html'
    title: 'Posts tagged :tag' # :tag is replaced by the tag name
    permalink: '/tags/:tag.html'
